# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Laplace approximation to the information matrix
#'
#' @description Approximates the information matrix for the model parameters 
#' using a Laplace Approximation. This is not intended to be directly used,
#' instead a user should use the \code{\link{PMLInfoApprox}} function with the "Laplace" option.
#'
#' @param ny Number of response samples to draw
#' @param X The model matrix
#' @param b_mean The vector of effect means
#' @param var_vec The vector of effect variances
#' @param n_choice_set The number of choice sets in the discrete choice experiment
#' @return A matrix containing the Laplace approximation to the variance covariance matrix of the model parameters
laplaceApproximation <- function(ny, X, b_mean, var_vec, n_choice_set) {
    .Call('_PanelMixedDesign_laplaceApproximation', PACKAGE = 'PanelMixedDesign', ny, X, b_mean, var_vec, n_choice_set)
}

#' Approximation to the information matrix using the method of simulated moments
#'
#' @description Approximates the information matrix for the model parameters 
#' using the method of simulated moments. This is not intended to be directly used,
#' instead a user should use the \code{\link{PMLInfoApprox}} function with 
#' the "MSM" option.
#'
#' @param ny Number of response samples to draw
#' @param X The model matrix
#' @param b_mean The vector of effect means
#' @param var_vec The vector of effect variances
#' @param nChoiceSet The number of choice sets in the discrete choice experiment
#' @return A matrix containing the MSM evaluated of the variance
#' covariance matrix of the model parameters
MSMApprox <- function(ny, X, b_mean, var_vec, nChoiceSet) {
    .Call('_PanelMixedDesign_MSMApprox', PACKAGE = 'PanelMixedDesign', ny, X, b_mean, var_vec, nChoiceSet)
}

#' Approximation to the information matrix using PQL
#'
#' @description Approximates the information matrix for the model parameters 
#' using the partial quasi likelihood. This is not intended to be directly used,
#' instead a user should use the \code{\link{PMLInfoApprox}} function with 
#' the "PQL" option.
#'
#' @param nu Number of samples to draw
#' @param X The model matrix
#' @param b_mean The vector of effect means
#' @param var_vec The vector of effect variances
#' @param nChoiceSet The number of choice sets in the discrete choice experiment
#' @return A matrix containing the PQL approximation to the variance
#' covariance matrix of the model parameters
PQLApprox <- function(nu, X, b_mean, var_vec, nChoiceSet) {
    .Call('_PanelMixedDesign_PQLApprox', PACKAGE = 'PanelMixedDesign', nu, X, b_mean, var_vec, nChoiceSet)
}

#' Approximate the information matrix using importance sampling
#'
#' @description Approximates the information matrix for the model parameters 
#' using importance sampling. This is not intended to be directly used,
#' instead a user should use the \code{\link{PMLInfoApprox}} function with 
#' the "importance" option.
#'
#' @param Y an enumeration of all possible responses. Can be obtained using
#'  the \code{\link{gen_all_choice_seq}} function
#' @param X The model matrix
#' @param b_mean The vector of effect means
#' @param var_vec The vector of effect variances
#' @param nChoiceSet The number of choice sets in the discrete choice experiment
#' @param nU Number of samples to use to evalutate the information matrix
#' @return A matrix containing the MSM evaluated of the variance
#' covariance matrix of the model parameters
importanceSampleFixedY <- function(Y, X, b_mean, var_vec, nChoiceSet, nU) {
    .Call('_PanelMixedDesign_importanceSampleFixedY', PACKAGE = 'PanelMixedDesign', Y, X, b_mean, var_vec, nChoiceSet, nU)
}

importanceSample <- function(X, b_mean, var_vec, nChoiceSet, nU, nY) {
    .Call('_PanelMixedDesign_importanceSample', PACKAGE = 'PanelMixedDesign', X, b_mean, var_vec, nChoiceSet, nU, nY)
}

