# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Laplace approximation to the information matrix
#'
#' @description Approximates the information matrix for the model parameters 
#' using a Laplace Approximation. This is not intended to be directly used,
#' instead a user should use the \code{\link{PMLInfoApprox}} function with the "Laplace" option.
#'
#' @param ny Number of response samples to draw
#' @param X The model matrix
#' @param b_mean The vector of effect means
#' @param var_vec The vector of effect variances
#' @param n_choice_set The number of choice sets in the discrete choice experiment
#' @return A matrix containing the Laplace approximation to the variance covariance matrix of the model parameters
laplaceApproximation <- function(ny, X, b_mean, var_vec, n_choice_set) {
    .Call('_PanelMixedDesign_laplaceApproximation', PACKAGE = 'PanelMixedDesign', ny, X, b_mean, var_vec, n_choice_set)
}

laplace_set_maxprob_Y_inplace <- function(Y, expXB, choice_set_size) {
    invisible(.Call('_PanelMixedDesign_laplace_set_maxprob_Y_inplace', PACKAGE = 'PanelMixedDesign', Y, expXB, choice_set_size))
}

laplace_u1_fn_minimize <- function(u0_mle, b_mean, OmegaRE, X, beta, prob, nRandEffect, nFixedEffect, nChoiceSet) {
    .Call('_PanelMixedDesign_laplace_u1_fn_minimize', PACKAGE = 'PanelMixedDesign', u0_mle, b_mean, OmegaRE, X, beta, prob, nRandEffect, nFixedEffect, nChoiceSet)
}

laplace_u1_gr_minimize <- function(u0_mle, b_mean, OmegaRE, X, beta, prob, nRandEffect, nFixedEffect, nChoiceSet) {
    .Call('_PanelMixedDesign_laplace_u1_gr_minimize', PACKAGE = 'PanelMixedDesign', u0_mle, b_mean, OmegaRE, X, beta, prob, nRandEffect, nFixedEffect, nChoiceSet)
}

laplace_usj_fn_minimize <- function(u0_mle, b_mean, OmegaRE, X, beta, prob, nRandEffect, nFixedEffect, nChoiceSet, irow, iCS, choice_set_size, X_cs_rdm) {
    .Call('_PanelMixedDesign_laplace_usj_fn_minimize', PACKAGE = 'PanelMixedDesign', u0_mle, b_mean, OmegaRE, X, beta, prob, nRandEffect, nFixedEffect, nChoiceSet, irow, iCS, choice_set_size, X_cs_rdm)
}

laplace_usj_evaluate_H <- function(u0j_mle, b_mean, OmegaRE, X, XR, beta, prob, nRandEffect, nFixedEffect, nChoiceSet, irow, iCS, choice_set_size, X_cs_rdm) {
    .Call('_PanelMixedDesign_laplace_usj_evaluate_H', PACKAGE = 'PanelMixedDesign', u0j_mle, b_mean, OmegaRE, X, XR, beta, prob, nRandEffect, nFixedEffect, nChoiceSet, irow, iCS, choice_set_size, X_cs_rdm)
}

laplace_uj_fn_minimize <- function(u, b_mean, sigma_re, OmegaRE, X, beta, prob, constant_term, nRandEffect, nFixedEffect, nChoiceSet, iRE, choice_set_size, X_cs_rdm) {
    .Call('_PanelMixedDesign_laplace_uj_fn_minimize', PACKAGE = 'PanelMixedDesign', u, b_mean, sigma_re, OmegaRE, X, beta, prob, constant_term, nRandEffect, nFixedEffect, nChoiceSet, iRE, choice_set_size, X_cs_rdm)
}

laplace_uj_evaluate_H <- function(u, b_mean, OmegaRE, sigma_re, X, XR, beta, prob, nRandEffect, nFixedEffect, nChoiceSet, iRE, choice_set_size, X_cs_rdm, constant_term) {
    .Call('_PanelMixedDesign_laplace_uj_evaluate_H', PACKAGE = 'PanelMixedDesign', u, b_mean, OmegaRE, sigma_re, X, XR, beta, prob, nRandEffect, nFixedEffect, nChoiceSet, iRE, choice_set_size, X_cs_rdm, constant_term)
}

#' Approximation to the information matrix using the method of simulated moments
#'
#' @description Approximates the information matrix for the model parameters 
#' using the method of simulated moments. This is not intended to be directly used,
#' instead a user should use the \code{\link{PMLInfoApprox}} function with 
#' the "MSM" option.
#'
#' @param ny Number of response samples to draw
#' @param X The model matrix
#' @param b_mean The vector of effect means
#' @param var_vec The vector of effect variances
#' @param nChoiceSet The number of choice sets in the discrete choice experiment
#' @return A matrix containing the MSM evaluated of the variance
#' covariance matrix of the model parameters
MSMApprox <- function(ny, X, b_mean, var_vec, nChoiceSet) {
    .Call('_PanelMixedDesign_MSMApprox', PACKAGE = 'PanelMixedDesign', ny, X, b_mean, var_vec, nChoiceSet)
}

#' Approximation to the information matrix using PQL
#'
#' @description Approximates the information matrix for the model parameters 
#' using the partial quasi likelihood. This is not intended to be directly used,
#' instead a user should use the \code{\link{PMLInfoApprox}} function with 
#' the "PQL" option.
#'
#' @param nu Number of samples to draw
#' @param X The model matrix
#' @param b_mean The vector of effect means
#' @param var_vec The vector of effect variances
#' @param nChoiceSet The number of choice sets in the discrete choice experiment
#' @return A matrix containing the PQL approximation to the variance
#' covariance matrix of the model parameters
PQLApprox <- function(nu, X, b_mean, var_vec, nChoiceSet) {
    .Call('_PanelMixedDesign_PQLApprox', PACKAGE = 'PanelMixedDesign', nu, X, b_mean, var_vec, nChoiceSet)
}

normalizeProbabilities <- function(probs, n_choice) {
    .Call('_PanelMixedDesign_normalizeProbabilities', PACKAGE = 'PanelMixedDesign', probs, n_choice)
}

update_response_probabilities_inplace <- function(prob, X, beta, n_choice) {
    invisible(.Call('_PanelMixedDesign_update_response_probabilities_inplace', PACKAGE = 'PanelMixedDesign', prob, X, beta, n_choice))
}

update_delta_inplace <- function(delta, p, n_choice_set) {
    invisible(.Call('_PanelMixedDesign_update_delta_inplace', PACKAGE = 'PanelMixedDesign', delta, p, n_choice_set))
}

impsamp_calc_info_given_Y <- function(Y, X, b_mean, var_vec, nChoiceSet, nU, return_unweighted, marginal_prob_store) {
    .Call('_PanelMixedDesign_impsamp_calc_info_given_Y', PACKAGE = 'PanelMixedDesign', Y, X, b_mean, var_vec, nChoiceSet, nU, return_unweighted, marginal_prob_store)
}

R_impsamp_calc_info_given_Y <- function(Y, X, b_mean, var_vec, nChoiceSet, nU, return_unweighted, marginal_prob_store) {
    .Call('_PanelMixedDesign_R_impsamp_calc_info_given_Y', PACKAGE = 'PanelMixedDesign', Y, X, b_mean, var_vec, nChoiceSet, nU, return_unweighted, marginal_prob_store)
}

#' Approximate the information matrix using importance sampling
#'
#' @description Approximates the information matrix for the model parameters 
#' using importance sampling. This is not intended to be directly used,
#' instead a user should use the \code{\link{PMLInfoApprox}} function with 
#' the "importance" option.
#'
#' @param Y an enumeration of all possible responses. Can be obtained using
#'  the \code{\link{gen_all_choice_seq}} function
#' @param X The model matrix
#' @param b_mean The vector of effect means
#' @param var_vec The vector of effect variances
#' @param nChoiceSet The number of choice sets in the discrete choice experiment
#' @param nU Number of samples to use to evalutate the information matrix
#' @return A matrix containing the MSM evaluated of the variance
#' covariance matrix of the model parameters
importanceSampleFixedY <- function(Y, X, b_mean, var_vec, nChoiceSet, nU) {
    .Call('_PanelMixedDesign_importanceSampleFixedY', PACKAGE = 'PanelMixedDesign', Y, X, b_mean, var_vec, nChoiceSet, nU)
}

importanceSample <- function(X, b_mean, var_vec, nChoiceSet, nU, nY) {
    .Call('_PanelMixedDesign_importanceSample', PACKAGE = 'PanelMixedDesign', X, b_mean, var_vec, nChoiceSet, nU, nY)
}

impsamp_calc_conditional_prob_vector_inplace_R <- function(condProbs, Y, probs, nChoiceSet) {
    invisible(.Call('_PanelMixedDesign_impsamp_calc_conditional_prob_vector_inplace_R', PACKAGE = 'PanelMixedDesign', condProbs, Y, probs, nChoiceSet))
}

impsamp_update_easy_terms_inplace <- function(Delta, PPt, PRatiosT, responseProbs, U22, X, b_mean, var_vec, nChoiceSet, nU) {
    invisible(.Call('_PanelMixedDesign_impsamp_update_easy_terms_inplace', PACKAGE = 'PanelMixedDesign', Delta, PPt, PRatiosT, responseProbs, U22, X, b_mean, var_vec, nChoiceSet, nU))
}

