# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Laplace approximation to the information matrix
NULL

Laplace_approx_vcov <- function(n_samples, X, b_mean, var_vec, n_choice_set) {
    .Call('_PanelMixedDesign_Laplace_approx_vcov', PACKAGE = 'PanelMixedDesign', n_samples, X, b_mean, var_vec, n_choice_set)
}

#' Approximation to the variance-covariance matrix for the panel mixed logit model using the method of simulated moments
#'
#' @description Approximates the variance covariance matrix for the model parameters 
#' using the method of simulated moments. This is not intended to be directly used,
#' instead a user should use the \code{\link{varcov_approx_PML}} function with 
#' the "MSM" option.
#'
#' @param n_samples Number of response samples to draw
#' @param X The model matrix
#' @param b_mean The vector of effect means
#' @param var_vec The vector of effect variances
#' @param n_choice_set The number of choice sets in the discrete choice experiment
#' @return A matrix containing the MSM evaluated approximation of the variance
#' covariance matrix of the model parameters
MSM_approx_vcov <- function(n_samples, X, b_mean, var_vec, n_choice_set) {
    .Call('_PanelMixedDesign_MSM_approx_vcov', PACKAGE = 'PanelMixedDesign', n_samples, X, b_mean, var_vec, n_choice_set)
}

#' Approximation to the information matrix using PQL
#'
#' @description Approximates the information matrix for the model parameters 
#' using partial quasilikelihood. This is not intended to be directly used,
#' instead a user should use the \code{\link{varcov_approx_PML}} function with 
#' the "PQL" option.
#'
#' @param n_samples Number of samples to draw
#' @param X The model matrix
#' @param b_mean The vector of effect means
#' @param var_vec The vector of effect variances
#' @param nChoiceSet The number of choice sets in the discrete choice experiment
#' @return A matrix containing the PQL approximation to the variance
#' covariance matrix of the model parameters
#' @keywords internal
PQL_approx_vcov <- function(n_samples, X, b_mean, var_vec, nChoiceSet) {
    .Call('_PanelMixedDesign_PQL_approx_vcov', PACKAGE = 'PanelMixedDesign', n_samples, X, b_mean, var_vec, nChoiceSet)
}

normalize_probabilities <- function(probs, n_choice) {
    .Call('_PanelMixedDesign_normalize_probabilities', PACKAGE = 'PanelMixedDesign', probs, n_choice)
}

#' Approximate the information matrix using importance sampling based on a complete enumeration of possible responses
NULL

#' Approximate the information matrix using importance sampling based on random samples of possible responses
NULL

impsamp_calc_info_given_Y <- function(Y, X, b_mean, var_vec, n_choice_set, n_samples_u, return_unweighted, marginal_prob_store) {
    .Call('_PanelMixedDesign_impsamp_calc_info_given_Y', PACKAGE = 'PanelMixedDesign', Y, X, b_mean, var_vec, n_choice_set, n_samples_u, return_unweighted, marginal_prob_store)
}

importance_sample_all_Y <- function(Y, X, b_mean, var_vec, n_choice_set, n_samples_u) {
    .Call('_PanelMixedDesign_importance_sample_all_Y', PACKAGE = 'PanelMixedDesign', Y, X, b_mean, var_vec, n_choice_set, n_samples_u)
}

importance_sample_random_Y <- function(X, b_mean, var_vec, n_choice_set, n_samples_u, n_samples_Y) {
    .Call('_PanelMixedDesign_importance_sample_random_Y', PACKAGE = 'PanelMixedDesign', X, b_mean, var_vec, n_choice_set, n_samples_u, n_samples_Y)
}

